name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: docker build -t isolated:${GITHUB_SHA::7} .
      - name: Run container
        run: docker run -d --name ${GITHUB_SHA::7} isolated:${GITHUB_SHA::7} 
      - name: Run tests
        run: docker exec ${GITHUB_SHA::7} "yarn hardhat:test" 
      # - name: Install solc
      #   run: wget https://github.com/ethereum/solidity/releases/download/v0.8.13/solc-static-linux && sudo mv solc-static-linux /usr/bin/solc && sudo chmod +x /usr/bin/solc
      # - uses: actions/checkout@v2
      # - name: Use Node.js
      #   uses: actions/setup-node@v2
      #   with: 
      #     node-version: "12.x"
      # - name: Install yarn
      #   run: npm install --global yarn
      # - name: Install dependencies
      #   run: yarn install
      # - name: Run hardhat test
      #   run: yarn hardhat:test
      # - name: Run compound test
      #   run: yarn test