name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        # Hack to get around failing "ethereumjs-abi The remote archive doesn't match the expected checksum" error
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: Check linting of solidity and typescript
        run: yarn lint

  build:
    runs-on: ubuntu-18.04
    env:
      FORK_MAINNET: ${{ secrets.FORK_MAINNET }}
      QUICK_NODE_KEY: ${{ secrets.QUICK_NODE_KEY }}
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Install deps
        run: yarn

      - name: Install solidity
        run: yarn global add solc@0.8.13

      - name: "Create env file"
        run: |
          touch .env
          echo FORK_MAINNET=${{ secrets.FORK_MAINNET }} >> .env
          echo QUICK_NODE_KEY=${{ secrets.QUICK_NODE_KEY }} >> .env

      - name: Run hardhat compile and tests coverage
        run: |
          source .env
          yarn hardhat:compile && yarn hardhat:coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "50 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
